plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.140'
}

neoForge {
    neoFormVersion = "1.21.1-20240808.144430"

    runs {
        client {
            client()
        }
    }
}

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
    maven {
        name 'Mojang'
        url 'https://libraries.minecraft.net'
    }
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

dependencies {
    compileOnly "org.jetbrains:annotations:24.0.1"
    compileOnly "net.neoforged.fancymodloader:loader:4.0.42"
    compileOnly "net.neoforged:neoforge:21.1.219"
}

jar {
    manifest {
        attributes(
                'FMLModType': "LIBRARY",
                'Specification-Title': "languagefixer",
                'Specification-Vendor': "Westernat",
                'Specification-Version': "1",
                'Implementation-Title': project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor': "Westernat",
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'Automatic-Module-Name': "org.mesdag.languagefixer"
        )
    }
}
